consumer-key: gmUABBaygrn5uSlELYmEEudwG
consumer-secret: oFMNyNbOwAH4ZiXsCz1ajy0VfFVCSAd3IyMyH2fHgmVAjVRcD0
access-token: 869539760116826113-EfauTqivmWo1V4P0MmxlEkvPR9nhLfh
access-secret:

# To enable debugging head over to TwitterAPI\TwitterAPIExchange,
# then see the text on line 6.